### ISSUE TITLE
When feature file has multiple scenarios present, the Browser is not initializing if one of the test is failed.

### ISSUE THREAD

**Issue by nikunj23190** [susnigdha1/PlaywrightTestAutomationFramework#2]
I am having two scenarios running under same feature file. 
When first scenario fails, the cucumber picks up second scenario for execution but i am getting **BeanCreationException**

 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.pageObject' defined in file [/Users/nikunjP/Automation-UI/target/test-classes/com/practice/pages/PageObject.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mastercard.ess.pages.PageObject]: Constructor threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.PlaywrightBrowser' defined in class path resource [com/practice/configuration/playwright/PlaywrightInitializer.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.mastercard.ess.configuration.playwright.PlaywrightBrowser]: Factory method 'init' threw exception; nested exception is java.lang.NullPointerException

**Comment by nikunj23190** [comment]
Root cause of above issue was, there was no @Before annotation in my Runner class. 

Added below code and it worked.

 @Before
    public void setUp() {
        if(System.getProperties().containsKey("browser")&&System.getProperties().containsKey("tracing")) {
            System.clearProperty("browser");
            System.clearProperty("tracing");
        }
        System.setProperty("browser","chrome");
        System.setProperty("tracing", String.valueOf(true));
        log.info("Passing browser property to PlaywrightBrowser bean");
    }
    
    
    I think it is better to keep the keys in the property file.

**Comment by susnigdha1** [comment]
Closing ticket based on the reporters latest comment.

**Comment by susnigdha1** [comment]
Closing the ticket based on reporters latest comment.
